import { Box, Typography } from "@mui/material";
import React from "react";
import CardReview from "./CardReview";

const reviews = [
  {
    review_id: 58700,
    external_review_site_url_id: 0,
    user_id: 100025,
    competitor_id: 0,
    contact_id: 0,
    review_url_img_web:
      "https://res.cloudinary.com/cmacha2/image/upload/v1673815649/oe_logo_trans_50_njhgzr.png",
    review_site: "OUTBOUNDENGINE",
    vertical: 0,
    rating: 5,
    review:
      "Wilma excelente realtor extremadamente profesional, pendiente de todo detalle, te aclara hasta la más mínima duda y ante todo buena persona recomendada 100% para vender o comprar casa. Estoy muy satisfecho con su servicio, Muchas gracias por tu ayuda.",
    first_name: "Andy",
    email: "andylopezyi@gamil.com",
    city: "Hialeah",
    state: "FL",
    country: "United States",
    date: "2022-04-25",
    deleted: false,
    hash_key: "74lOrxO6ZrDyQaymFKcb_g",
    approved: true,
    show_nickname: false,
    display_name: "Andy ",
  },
  {
    review_id: 1328384,
    external_review_site_url_id: 113789,
    user_id: 100025,
    competitor_id: 0,
    contact_id: 0,
    review_url_img_web:
      "https://res.cloudinary.com/cmacha2/image/upload/v1673815663/zillow_logo_praak2.png",
    review_site: "ZILLOW",
    vertical: 0,
    rating: 5,
    review:
      "Wilma excelente realtor extremadamente profesional, pendiente de todo detalle, te aclara hasta la más mínima duda y ante todo buena persona recomendada 100% para vender o comprar casa. Estoy muy satisfecho con su servicio, Muchas gracias por tu ayuda.",
    first_name: "andylopezyi",
    url: "https://www.zillow.com/profile/user30313729",
    date: "2022-04-24",
    deleted: false,
    hash_key: "VEM38H_kbe3KZBkGp4iA0Q",
    approved: true,
    show_nickname: true,
    display_name: "andylopezyi ",
  },
  {
    review_id: 57860,
    external_review_site_url_id: 0,
    user_id: 100025,
    competitor_id: 0,
    contact_id: 0,
    review_url_img_web:
      "https://res.cloudinary.com/cmacha2/image/upload/v1673815649/oe_logo_trans_50_njhgzr.png",
    review_site: "OUTBOUNDENGINE",
    vertical: 0,
    rating: 5,
    first_name: "Shirley ",
    last_name: "Ortiz",
    email: "shimoa0414@gmail.com",
    phone: "786-443-8589",
    city: "Hialeah",
    state: "FL",
    country: "United States",
    date: "2022-03-18",
    deleted: false,
    hash_key: "ynjbv94uJKLa0DsT1Ar_XQ",
    approved: true,
    show_nickname: false,
    display_name: "Shirley  Ortiz",
  },
  {
    review_id: 57866,
    external_review_site_url_id: 0,
    user_id: 100025,
    competitor_id: 0,
    contact_id: 0,
    review_url_img_web:
      "https://res.cloudinary.com/cmacha2/image/upload/v1673815649/oe_logo_trans_50_njhgzr.png",
    review_site: "OUTBOUNDENGINE",
    vertical: 0,
    rating: 5,
    review:
      "Wilma is an extraordinary person, very professional, kind, helpful, caring & loving. She has helped me in rentals as well with the association.  Overall she is very efficient and will do anything in her meeds to help you.",
    first_name: "Shirley",
    last_name: "Ortiz",
    email: "shimoa0414@gmail.com",
    phone: "786-443-8589",
    city: "Hialeah",
    state: "FL",
    country: "United States",
    date: "2022-03-18",
    deleted: false,
    hash_key: "U2qI_x4i0eE8JnBwadHweQ",
    approved: true,
    show_nickname: false,
    display_name: "Shirley Ortiz",
  },
  {
    review_id: 1251230,
    external_review_site_url_id: 114755,
    user_id: 100025,
    competitor_id: 0,
    contact_id: 0,
    review_url_img_web:
      "https://res.cloudinary.com/cmacha2/image/upload/v1673815679/googlereviews_logo_l7l462.png",
    review_site: "GOOGLE_REVIEWS",
    vertical: 0,
    rating: 5,
    review:
      "VERY RESOURCEFUL! As an investor, I look for DEALS. She knows where to find the best deals.",
    first_name: "Denise",
    last_name: "Martinez",
    nickname: "Denise Martinez",
    url: "https://www.google.com/search?q=Wilma+Alvarez+-+Realtor%2C+Miami+Lakes+Drive%2C+Miami+Lakes%2C+FL&ludocid=52518146724753623#lrd=0x88d9a5e5878d7227:0xba94f9e7ca70d7,1",
    date: "2021-11-18",
    deleted: false,
    hash_key: "pDbJuGd81qmifFSO6CXu5w",
    approved: true,
    show_nickname: true,
    display_name: "Denise Martinez",
  },
  {
    review_id: 1250906,
    external_review_site_url_id: 113789,
    user_id: 100025,
    competitor_id: 0,
    contact_id: 0,
    review_url_img_web:
      "https://res.cloudinary.com/cmacha2/image/upload/v1673815663/zillow_logo_praak2.png",
    review_site: "ZILLOW",
    vertical: 0,
    rating: 5,
    review:
      "VERY RESOURCEFUL!  As an investor, I always look for DEALS. She knows where to find the best deals. She is amazing, very knowledgeable, professional.  I would definitely recommend to my friends and family members.",
    first_name: "dmartinez900",
    city: "Hollywood",
    state: "FL",
    url: "https://www.zillow.com/profile/user30313729",
    date: "2021-11-17",
    deleted: false,
    hash_key: "ZowxsP_4Y3Sj130PcipjYQ",
    approved: true,
    show_nickname: true,
    display_name: "dmartinez900 ",
  },
  {
    review_id: 1248779,
    external_review_site_url_id: 114755,
    user_id: 100025,
    competitor_id: 0,
    contact_id: 0,
    review_url_img_web:
      "https://res.cloudinary.com/cmacha2/image/upload/v1673815679/googlereviews_logo_l7l462.png",
    review_site: "GOOGLE_REVIEWS",
    vertical: 0,
    rating: 5,
    review:
      "Wilma is a very professional realtor. She save my business and fight for me like anyone. I highly recommended her as a realtor. Best realtor I ever know.",
    first_name: "Osmany",
    last_name: "Silva",
    nickname: "Osmany Silva",
    url: "https://www.google.com/search?q=Wilma+Alvarez+-+Realtor%2C+Miami+Lakes+Drive%2C+Miami+Lakes%2C+FL&ludocid=52518146724753623#lrd=0x88d9a5e5878d7227:0xba94f9e7ca70d7,1",
    date: "2021-10-22",
    deleted: false,
    hash_key: "8zG4ajWWRshdGTei0Ov3Dg",
    approved: true,
    show_nickname: true,
    display_name: "Osmany Silva",
  },
  {
    review_id: 1236467,
    external_review_site_url_id: 113789,
    user_id: 100025,
    competitor_id: 0,
    contact_id: 0,
    review_url_img_web:
      "https://res.cloudinary.com/cmacha2/image/upload/v1673815663/zillow_logo_praak2.png",
    review_site: "ZILLOW",
    vertical: 0,
    rating: 5,
    review:
      "We were looking to add one more property to our portfolio in this high demand market. Wilma Álvarez gave us her best to fulfill our requirements. I recommend 100 % Wilma if you want a real estate that truly understand the buyer's or seller needs.",
    first_name: "Yasser",
    last_name: "Martinez",
    nickname: "Yasser Martinez",
    city: "Miami",
    state: "FL",
    url: "https://www.zillow.com/profile/user30313729",
    date: "2021-10-17",
    deleted: false,
    hash_key: "DI2ZOjjKuQ3pBlAuau_wwA",
    approved: true,
    show_nickname: true,
    display_name: "Yasser Martinez",
  },
  {
    review_id: 1235495,
    external_review_site_url_id: 113789,
    user_id: 100025,
    competitor_id: 0,
    contact_id: 0,
    review_url_img_web:
      "https://res.cloudinary.com/cmacha2/image/upload/v1673815663/zillow_logo_praak2.png",
    review_site: "ZILLOW",
    vertical: 0,
    rating: 5,
    review:
      "Wilma is a professional from word go.  She communicates with everyone to ensure the closing experience is smooth.  She is the glue that holds everything together.  I look forward to working with her again!You will never be disappointed working with Wilma whether you want to buy/sell!!",
    first_name: "debbie89660",
    url: "https://www.zillow.com/profile/user30313729",
    date: "2021-10-15",
    deleted: false,
    hash_key: "q2nXOHO8wSHHUXJsn3n5Zg",
    approved: true,
    show_nickname: true,
    display_name: "debbie89660 ",
  },
  {
    review_id: 1236470,
    external_review_site_url_id: 113789,
    user_id: 100025,
    competitor_id: 0,
    contact_id: 0,
    review_url_img_web:
      "https://res.cloudinary.com/cmacha2/image/upload/v1673815663/zillow_logo_praak2.png",
    review_site: "ZILLOW",
    vertical: 0,
    rating: 5,
    review:
      "Wilma is a very professional realtor. She save my business when I got my first apartment and fight for me like anyone. I highly recommended her as a realtor. Best realtor I ever know.",
    first_name: "OsmanySilva",
    city: "Miami",
    state: "FL",
    url: "https://www.zillow.com/profile/user30313729",
    date: "2021-10-15",
    deleted: false,
    hash_key: "5Jr8gYv1o84K6aAdrXdoeA",
    approved: true,
    show_nickname: true,
    display_name: "OsmanySilva ",
  },
  {
    review_id: 1445692,
    external_review_site_url_id: 113789,
    user_id: 100025,
    competitor_id: 0,
    contact_id: 0,
    review_url_img_web:
      "https://res.cloudinary.com/cmacha2/image/upload/v1673815663/zillow_logo_praak2.png",
    review_site: "ZILLOW",
    vertical: 0,
    rating: 5,
    review:
      "Wilma is a very professional realtor. She save my business when I got my first apartment and fight for me like anyone. I highly recommended her as a realtor. Best realtor I ever know.",
    first_name: "Osmani",
    last_name: "Silva",
    nickname: "Osmani Silva",
    city: "Miami",
    state: "FL",
    url: "https://www.zillow.com/profile/user30313729",
    date: "2021-10-15",
    deleted: false,
    hash_key: "AkFfiqQ-0SYGpdCu7ByOTQ",
    approved: true,
    show_nickname: true,
    display_name: "Osmani Silva",
  },
  {
    review_id: 1235594,
    external_review_site_url_id: 114758,
    user_id: 100025,
    competitor_id: 0,
    contact_id: 0,
    review_url_img_web:
      "https://res.cloudinary.com/cmacha2/image/upload/v1673815696/yelp_logo_ubld52.png",
    review_site: "YELP",
    vertical: 0,
    rating: 5,
    review:
      "Wilma is a professional from word go.  She communicates with everyone to ensure the closing experience is smooth.  She is the glue that holds everything together.  I look forward to working with her again!\nYou will never be disappointed working with Wilma whether you want to buy/sell!!",
    first_name: "Debra",
    last_name: "A.",
    nickname: "Debra A.",
    city: "Riviera Beach",
    state: "FL",
    url: "https://www.yelp.com/biz/wilma-alvarez-empire-realty-of-florida-hialeah-2?hrid=cyM3JbpKwCUFyN9p0z7F6A",
    date: "2021-10-15",
    deleted: false,
    hash_key: "fn5JZMFUwvVQwD-giyVfCA",
    approved: true,
    show_nickname: true,
    display_name: "Debra A.",
  },
  {
    review_id: 1233065,
    external_review_site_url_id: 114758,
    user_id: 100025,
    competitor_id: 0,
    contact_id: 0,
    review_url_img_web:
      "https://res.cloudinary.com/cmacha2/image/upload/v1673815696/yelp_logo_ubld52.png",
    review_site: "YELP",
    vertical: 0,
    rating: 5,
    review: "Committed , dedicated and EXTREMELY knowledgeable Realtor !",
    first_name: "Meyling",
    last_name: "M.",
    nickname: "Meyling M.",
    city: "Hollywood",
    state: "FL",
    url: "https://www.yelp.com/biz/wilma-alvarez-empire-realty-of-florida-hialeah-2?hrid=d92jhOgbDzg28c8QhKCtiQ",
    date: "2021-10-11",
    deleted: false,
    hash_key: "uTH3fgCOC9A04XBGKRgsQA",
    approved: true,
    show_nickname: true,
    display_name: "Meyling M.",
  },

  {
    review_id: 1220444,
    external_review_site_url_id: 114758,
    user_id: 100025,
    competitor_id: 0,
    contact_id: 0,
    review_url_img_web:
      "https://res.cloudinary.com/cmacha2/image/upload/v1673815696/yelp_logo_ubld52.png",
    review_site: "YELP",
    vertical: 0,
    rating: 5,
    review:
      "As a real estate agent I have worked several times with Wilma Alvarez. She has always been professional and is very knowledgeable . I would highly recommend her and her company for any real estate needs.!",
    first_name: "Andrea",
    last_name: "F.",
    nickname: "Andrea F.",
    city: "Hialeah",
    state: "FL",
    url: "https://www.yelp.com/biz/wilma-alvarez-empire-realty-of-florida-hialeah-2?hrid=E4RTo3nQBIg6P08ozb7mEQ",
    date: "2021-09-15",
    deleted: false,
    hash_key: "WUE9Iknd2C01Qoy0mf7u2w",
    approved: true,
    show_nickname: true,
    display_name: "Andrea F.",
  },
  {
    review_id: 1208759,
    external_review_site_url_id: 113789,
    user_id: 100025,
    competitor_id: 0,
    contact_id: 0,
    review_url_img_web:
      "https://res.cloudinary.com/cmacha2/image/upload/v1673815663/zillow_logo_praak2.png",
    review_site: "ZILLOW",
    vertical: 0,
    rating: 5,
    review:
      "Over all pleasant very she was very knowledgeable and available for all our questions also she is very resourceful and can get buyers to the negotiation table quickly",
    first_name: "user1834506",
    city: "Miami",
    state: "FL",
    url: "https://www.zillow.com/profile/user30313729",
    date: "2013-08-01",
    deleted: false,
    hash_key: "pz9V--QghafNLG-2EyNoSA",
    approved: true,
    show_nickname: true,
    display_name: "user1834506 ",
  },
];

function SessionReviews() {
  return (
    <Box
      sx={{
        padding: "1rem",
        textAlign: "center",
      }}
    >
      <Box>
        <Typography variant="h4" sx={{ paddingY: 5 }}>
          Reviews
        </Typography>
      </Box>
      <Box sx={{ display: "flex", gap: 5, justifyContent: "center", flexWrap:'wrap',flexGrow:3 }}>
       {
        reviews.map(review => (<CardReview review={review}/>))
        }
      </Box>
    </Box>
  );
}

export default SessionReviews;
